### ISSUE TITLE
I use this template for my academic page

### ISSUE THREAD

**Issue by hosseinpro** [mavroudisv/plain-academic#1]
https://www.cs.ucf.edu/~rezaei

**Comment by mavroudisv** [comment]
Nice! Happy to add you to the list! Can you please make sure that the link works? I get an error message.

**Comment by hosseinpro** [comment]
The stylesheet, jQuery and bootstrap http links work on the local server but not on the real server. I changed them to https and it works now.

**Comment by mavroudisv** [comment]
Added!
